version: '2.1'

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps
    environment:
      DOCKER_BUILDKIT: '1'
    steps:
      - checkout
      - run: echo $CIRCLE_BRANCH

workflows:
  version: 2
  build:
    jobs:
      - build
